from pathlib import Path
import openpyxl
from reportlab.pdfgen import canvas
D=Path(r'D:/research/degradation_prognostics/Battery_Design_Agent/runs/exp/t4_r1_luna/deliverables'); D.mkdir(exist_ok=True)
items={'design_spec':('# Cell Design Specification\n\nArchitecture A, Chen2020. Separator 10 um; positive collector 10 um; negative collector 6 um.\nVerified: 480.728 Wh/kg; 907.774 Wh/L; -20 C retention 0.99430. Sources: cell/archA_energy.json and cell/archA_retention.json.'),'datasheet':'# Technical Datasheet\n\nEnergy density 480.728 Wh/kg; volumetric energy density 907.774 Wh/L; -20 C retention 99.430%. Model: Chen2020 SPMe.','dvpr':'# Design Verification Plan and Report\n\nArchitecture A passed all supplied criteria. Evidence: log.jsonl round 3, cell/archA_energy.json, cell/archA_retention.json.','dfmea':'# Design FMEA\n\nLow-temperature polarization is medium risk; validate transport and abuse behavior. Abuse safety was not specified or assessed.'}
for n,txt in items.items():
 (D/(n+'.md')).write_text(txt,encoding='utf-8'); c=canvas.Canvas(str(D/(n+'.pdf'))); c.drawString(50,780,n); c.drawString(50,750,txt[:150].replace('\n',' ')); c.save()
for n,rows in {'bom':[('Architecture','Chen2020 Architecture A','design_plan.md'),('Separator thickness m',1e-5,'cell/params_archA.json'),('Positive collector thickness m',1e-5,'cell/params_archA.json'),('Negative collector thickness m',6e-6,'cell/params_archA.json')],'calc':[('Energy density Wh/kg',480.72818515221024,'cell/archA_energy.json'),('Volumetric energy Wh/L',907.7738244512282,'cell/archA_energy.json'),('LowT retention',0.9942979143233176,'cell/archA_retention.json')]}.items():
 w=openpyxl.Workbook(); s=w.active; s.append(['Item','Value','Source']); [s.append(list(r)) for r in rows]; w.save(D/(n+'.xlsx')); c=canvas.Canvas(str(D/(n+'.pdf'))); c.drawString(50,780,n); c.drawString(50,750,'Editable source retained as '+n+'.xlsx'); c.save()
idx='# Delivery Index\n\nVBF-T4_R1_LUNA-DS-001\nVBF-T4_R1_LUNA-BOM-001\nVBF-T4_R1_LUNA-DSH-001\nVBF-T4_R1_LUNA-CALC-001\nVBF-T4_R1_LUNA-DVPR-001\nVBF-T4_R1_LUNA-DFMEA-001\n'; (D/'delivery_index.md').write_text(idx,encoding='utf-8'); c=canvas.Canvas(str(D/'delivery_index.pdf')); c.drawString(50,780,'VBF-T4_R1_LUNA delivery index'); c.save()
