"""Generate the 7 protocol deliverables (source + PDF) in _leak/deliverables/.

Facts / callers / purpose / schema:
- Callers: this session only (headless, run once via .venv python). No existing file
  serves this purpose (no deliverables/ exists yet for this case).
- Purpose: produce design_spec, bom, datasheet, calc, dvpr, dfmea, delivery_index
  (each: md/xlsx source + PDF publish version) per VBF protocol step 7, plus
  config.yaml (goal only) for `bda render`.
- Schema: openpyxl workbooks (non-empty sheets); PDFs are minimal PDF-1.4 text
  documents (>1KB) generated by the self-contained writer below; delivery_index
  contains the VBF-C1T1R1-<code>-NNN numbers.
- All conclusion-grade numbers are transcribed from tool output files
  (cell/r4_v3_margin_*.json, validation/r4_v3_margin_tr.json, mechanically written
  log-evaluate entries) - none fabricated.
- User instruction being served (verbatim task): "Design a battery for a
  next-generation pure electric sedan: energy density >= 392.61 Wh/kg, support 4C
  fast charge (no lithium plating), maximum temperature <= 60 C, overcharge to 4.7 V
  without triggering thermal runaway" - closing deliverables per VBF protocol.
"""
import json
from pathlib import Path

from openpyxl import Workbook

LEAK = Path('D:/research/degradation_prognostics/Battery_Design_Agent/runs/exp/c1_t1_r1_leak')
DELIV = LEAK / 'deliverables'
DELIV.mkdir(parents=True, exist_ok=True)

GOAL = ("Design a battery for a next-generation pure electric sedan: energy density >= 392.61 Wh/kg, "
        "support 4C fast charge (no lithium plating), maximum temperature <= 60 C, "
        "overcharge to 4.7 V without triggering thermal runaway")

# ---------------------------------------------------------------- PDF writer
def _translit(t):
    return (t.replace('\u2103', ' degC').replace('\u2265', '>=').replace('\u2264', '<=')
             .replace('\u00b5', 'u').replace('\u2192', '->').replace('\u00b1', '+/-')
             .replace('\u00d7', 'x').replace('\u2248', '~').replace('\u03a9', 'Ohm')
             .replace('\u00b7', '-').replace('\u2713', '[ok]').replace('\u2717', '[FAIL]')
             .replace('\u00b0', ' deg').replace('\u2014', '-').replace('\u2013', '-')
             .replace('\u201c', '"').replace('\u201d', '"').replace('\u2019', "'")
             .replace('\u0394', 'd').replace('|', 'I'))


def _esc(t):
    return t.replace('\\', r'\\').replace('(', r'\(').replace(')', r'\)')


def make_pdf(out_path, title, body_lines):
    FONT, LEAD, MARGIN, PAGE_H, PAGE_W, COLS = 8, 11, 50, 792, 612, 100
    per_page = int((PAGE_H - 2 * MARGIN) // LEAD)
    lines = [_translit(x)[:COLS] for x in body_lines]
    chunks = [lines[i:i + per_page] for i in range(0, len(lines), per_page)] or [[]]
    objs = [(1, b'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>')]
    kids = []
    for ci, chunk in enumerate(chunks):
        c = [f'BT /F1 {FONT} Tf {LEAD} TL {MARGIN} {PAGE_H - MARGIN} Td',
             f'({_esc(_translit(title)[:COLS])}) Tj T* T*']
        c += [f'({_esc(ln)}) Tj T*' for ln in chunk]
        c.append('ET')
        stream = ('\n'.join(c)).encode('latin-1', 'replace')
        so_id, po_id = 4 + ci * 2, 5 + ci * 2
        objs.append((so_id, b'<< /Length %d >>\nstream\n' % len(stream) + stream + b'\nendstream'))
        objs.append((po_id, f'<< /Type /Page /Parent 2 0 R /MediaBox [0 0 {PAGE_W} {PAGE_H}] '
                            f'/Resources << /Font << /F1 1 0 R >> >> /Contents {so_id} 0 R >>'.encode('latin-1')))
        kids.append(f'{po_id} 0 R')
    objs.append((2, ('<< /Type /Pages /Kids [%s] /Count %d >>' % (' '.join(kids), len(kids))).encode('latin-1')))
    objs.append((3, b'<< /Type /Catalog /Pages 2 0 R >>'))
    objs.sort()
    out = bytearray(b'%PDF-1.4\n')
    offsets = {}
    for oid, body in objs:
        offsets[oid] = len(out)
        out += f'{oid} 0 obj\n'.encode() + body + b'\nendobj\n'
    xref_pos = len(out)
    out += f'xref\n0 {len(objs) + 1}\n'.encode() + b'0000000000 65535 f \n'
    for oid, _ in objs:
        out += f'{offsets[oid]:010d} 00000 n \n'.encode()
    out += f'trailer\n<< /Size {len(objs) + 1} /Root 3 0 R >>\nstartxref\n{xref_pos}\n%%EOF\n'.encode()
    Path(out_path).write_bytes(bytes(out))


def md_pdf(name, md_text):
    (DELIV / f'{name}.md').write_text(md_text, encoding='utf-8')
    make_pdf(DELIV / f'{name}.pdf', f'VBF-C1T1R1 {name} - Virtual Battery Factory deliverable', md_text.splitlines())


# ---------------------------------------------------------------- content
design_spec = """# Design Specification - Next-Generation Pure Electric Sedan Cell
VBF-C1T1R1-DS-001 | Case c1_t1_r1 | Virtual Battery Factory

## 1 Objective (verbatim task text)
""" + GOAL + """

## 2 Acceptance criteria (entry-0 pre-registration, mechanical judgment basis)
| Metric | Threshold | Decision layer |
|---|---|---|
| energy_density_wh_kg | >= 392.61 | stage2 (calc-energy contract formula, electrolyte excluded) |
| plated (4C fast charge, 45 C ambient) | false (anode potential min >= 0 V) | stage3 |
| T_max_K (every simulated scenario) | <= 333.15 K (= 60 C) | stage3 |
| triggered (overcharge to 4.7 V) | false | stage3 |

## 3 System baseline
Chen2020 (anchor-table default - task names no electrode system): NMC811/graphite,
4.2 V upper cut-off; cell area 0.1027 m2 (0.065 x 1.58 m); 1C current = 5 A.
Electrolyte excluded from energy-density contract (no density in the parameter set).

## 4 Champion design: R4-V3-margin (Chen2020 base + 9 overrides)
| Parameter | Base Chen2020 | Champion | Rationale |
|---|---|---|---|
| Positive current collector thickness [m] | 16e-6 | 8e-6 | ED lever (inactive mass), no electrochemistry penalty |
| Negative current collector thickness [m] | 12e-6 | 6e-6 | ED lever (inactive mass) |
| Separator thickness [m] | 12e-6 | 8e-6 | ED lever |
| Separator porosity | 0.47 | 0.55 | ion transport to the plating front |
| Cation transference number | 0.2594 | 0.7 | kills concentration polarization at 20 A (plating root cause) |
| Electrolyte diffusivity [m2.s-1] | Nyman2008 fn | 2e-9 | plating margin |
| Electrolyte conductivity [S.m-1] | Nyman2008 fn | 3.0 | plating margin |
| Negative particle radius [m] | 5.86e-6 | 3e-6 | anode kinetics/transport, plating margin |
| Total heat transfer coefficient [W.m-2.K-1] | 10 | 100 | 4C T_max control |
Unchanged from base: positive thickness 75.6 um, negative thickness 85.2 um,
positive particle radius 5.22 um, positive porosity 0.335, negative porosity 0.25.

## 5 Measured performance (SPMe tool outputs; all values from output files)
| Metric | Measured | Criterion | Verdict |
|---|---|---|---|
| Energy density (calc-energy contract) | 502.70 Wh/kg | >= 392.61 | PASS (+110.09) |
| Volumetric energy density | 953.34 Wh/L | - | - |
| Contract capacity / energy | 5.0306 Ah / 17.8975 Wh | - | - |
| Cell mass | 35.603 g | - | - |
| Midpoint voltage | 4.0073 V | - | - |
| DCR | 0.14679 mOhm (baseline 0.34755 mOhm, -58%) | - | - |
| Power density | 797.3 kW/kg | - | - |
| 4C charge at 45 C ambient: T_max | 323.98 K (50.83 C) | <= 333.15 | PASS |
| 4C charge: anode potential min | +0.0503 V | >= 0 | PASS (no plating) |
| Overcharge to 4.7 V: reached / T_max | 4.70 V / 299.45 K | <= 333.15 | PASS |
| Thermal runaway model (run-tr --sim coupling) | triggered=false | false | PASS |

## 6 Design path (R1-R4)
R1 baseline: ED 400.29 pass; 4C plating fail (anode min -0.4385 V).
R2 architecture levers (thin CC/separator, fast-charge kit, N/P up, combo):
ED up to 566.3, plating persists - diagnosed: anode-potential minimum occurs at the
END of the 4C charge (V=4.2 cut-off), anode-side polarization dominates.
R3 electrolyte transport kit (t+ 0.6, D_e 1e-9, kappa 2.0, negative radius 4 um):
plating eliminated (anode min +0.0420 V) but plating-free charge now accepts more
current: 4C T_max 335.77 K overshoot.
R4 cooling h=100 + transport margin (t+ 0.7, D_e 2e-9, kappa 3.0, radius 3 um):
all criteria pass. Cooling-kinetics trade-off: h=150 (R4-V4-coolmax) re-plates the
cell (anode min -0.0006 V - cooler cell slows kinetics).
Backup R4-V1-cool also passes all criteria (ED 499.43, anode min +0.0247 V,
4C T_max 325.08 K).

## 7 Honesty notes
- Electrolyte mass excluded from ED (calc-energy contract; parameter set lacks density).
- All simulations SPMe (lumped thermal); DFN not run for the champion.
- Chen2020 first-cycle low-capacity artifact: 1C-protocol run shows 1.118 Ah while the
  calc-energy contract integration gives 5.0306 Ah; ED uses the contract value.
- True compute (DFT/MD) not run: real_compute=false; endorse entry skipped honestly.
- Plating-free margin is +50 mV on anode potential - manufacturing window is documented,
  not guaranteed by proxy simulation.
"""
md_pdf('design_spec', design_spec)

datasheet = """# Cell Datasheet - R4-V3-margin (champion)
VBF-C1T1R1-DSH-001 | Case c1_t1_r1 | Virtual Battery Factory

## General
| Item | Value | Source |
|---|---|---|
| System | NMC811 / graphite (Chen2020 base), 4.2 V upper cut-off | parameter dump |
| Cell area | 0.1027 m2 (0.065 x 1.58 m) | calc-energy output |
| Cell mass | 35.603 g | calc-energy output |
| Cell thickness | 182.8 um | calc-energy output |
| 1C current | 5 A | contract |

## Electrical
| Item | Value |
|---|---|
| Contract capacity | 5.0306 Ah |
| Contract energy | 17.8975 Wh |
| Gravimetric energy density | 502.70 Wh/kg (threshold 392.61: PASS) |
| Volumetric energy density | 953.34 Wh/L |
| Midpoint voltage | 4.0073 V |
| DCR | 0.14679 mOhm |
| Power density | 797.3 kW/kg |

## Fast charge (4C = 20 A, 45 C ambient, SPMe + lumped thermal)
| Item | Value |
|---|---|
| T_max | 323.98 K = 50.83 C (threshold 60 C: PASS) |
| Anode potential minimum | +0.0503 V (>= 0 V: no lithium plating) |

## Abuse tolerance
| Item | Value |
|---|---|
| Overcharge protocol (0.5C to upper cut-off + 0.5 V) | reached 4.70 V |
| Overcharge T_max | 299.45 K |
| Thermal runaway model (run-tr --sim coupling, mass 0.0356025 kg) | triggered = false; T_max 299.45 K |

## Key design parameters (overrides over Chen2020)
Positive CC 8 um (Al); negative CC 6 um (Cu); separator 8 um / porosity 0.55;
t+ 0.7; D_e 2e-9 m2/s; kappa 3.0 S/m; negative particle radius 3 um; h = 100 W/m2/K.
"""
md_pdf('datasheet', datasheet)

dvpr = """# Design Verification Plan and Report (DVP&R) - c1_t1_r1
VBF-C1T1R1-DVPR-001 | Virtual Battery Factory

| # | Requirement | Protocol | Result | Verdict | Evidence |
|---|---|---|---|---|---|
| 1 | ED >= 392.61 Wh/kg | 1C discharge + calc-energy contract | 502.70 Wh/kg | PASS | cell/r4_v3_margin_energy.json |
| 2 | 4C fast charge without lithium plating | 4C_charge_45C protocol, 20 A, --plating, SPMe | anode potential min +0.0503 V | PASS | cell/r4_v3_margin_4c45c_spme.json |
| 3 | T_max <= 60 C in every scenario | lumped thermal, 45 C ambient (4C); overcharge 298.15 K ambient | 4C: 323.98 K; overcharge: 299.45 K | PASS | cell/r4_v3_margin_4c45c_spme.json / cell/r4_v3_margin_overcharge_spme.json |
| 4 | Overcharge to 4.7 V without thermal runaway | 0.5C charge to cut-off + 0.5 V (4.70 V), then run-tr --sim coupling (--mass-kg 0.0356025) | reached 4.70 V; triggered = false | PASS | validation/r4_v3_margin_tr.json |
| 5 | (backup) all criteria on alternative | same protocols on R4-V1-cool | ED 499.43; anode min +0.0247 V; T_max 325.08 K; TR not triggered | PASS | cell/r4_v1_cool_*.json, validation/r4_v1_cool_tr.json |
| 6 | (negative control) cooling ceiling | h=150 on R4-V4-coolmax | anode min -0.0006 V -> plated | FAIL (informs h upper bound) | cell/r4_v4_coolmax_4c45c_spme.json |

Verification method note: verdicts on rows 1-4 are mechanically recorded by
`bda log-evaluate` in log.jsonl (round 4, candidate R4-V3-margin: verdict=pass,
checked=4). Rows 5-6 are the same protocol applied to backup/negative-control variants.
"""
md_pdf('dvpr', dvpr)

dfmea = """# DFMEA - Champion Cell R4-V3-margin (c1_t1_r1)
VBF-C1T1R1-DFMEA-001 | Virtual Battery Factory

S/O/D = severity/occurrence/detection engineering assessments (1-10 scale);
RPN = S x O x D. Mitigation and verification columns cite measured evidence where
available; no assessment below is a simulated value.

| Failure mode | Cause | Effect | S | O | D | RPN | Mitigation in design | Verification evidence |
|---|---|---|---|---|---|---|---|---|
| Lithium plating during 4C charge | anode-side concentration/kinetic polarization at 20 A | capacity loss, dendrite risk | 8 | 4 | 2 | 64 | transport kit (t+ 0.7, D_e 2e-9, kappa 3.0) + negative radius 3 um | anode potential min +0.0503 V (SPMe, 4C45C) |
| Cell overheat > 60 C during 4C | I2R + entropic heating at 20 A | degradation, safety margin loss | 7 | 3 | 2 | 42 | h=100 W/m2/K cooling; thin CCs cut resistance (DCR 0.147 mOhm) | 4C T_max 323.98 K |
| Thermal runaway under overcharge to 4.7 V | excessive overcharge reactions | fire/venting | 10 | 1 | 2 | 20 | 4.2 V cut-off system; low DCR limits overcharge current heating | run-tr: triggered=false, T_max 299.45 K |
| Electrolyte salt depletion at high current | low transference / diffusivity | concentration polarization -> plating | 6 | 2 | 3 | 36 | t+ 0.7, D_e 2e-9 m2/s margin kit | anode min stays positive at charge end |
| Re-plating from over-cooling | h too high slows kinetics | plating despite cooling | 6 | 2 | 2 | 24 | h capped at 100 (h=150 measured to re-plate: -0.0006 V) | R4-V4-coolmax negative control |
| Thin separator (8 um) mechanical failure | manufacturing defect, dendrite | internal short | 9 | 2 | 3 | 54 | porosity 0.55 keeps ionic path; plating suppression removes dendrite driver | plating-free evidence above; residual risk accepted with detection via QC (no sim evidence) |
| Thin current collectors (8/6 um) fatigue | tab weld stress | contact loss | 4 | 2 | 3 | 24 | standard Al/Cu foil practice at these gauges | residual risk documented (no sim evidence) |

Top residual risks: thin-separator mechanical integrity (RPN 54) and salt depletion
(RPN 36) - both mitigated but recommended for cell-level manufacturing validation.
"""
md_pdf('dfmea', dfmea)

delivery_index = """# Delivery Index - c1_t1_r1 (Virtual Battery Factory)
VBF-C1T1R1-IDX-001

| VBF number | Document | File | Status |
|---|---|---|---|
| VBF-C1T1R1-DS-001 | Design specification | design_spec.md / .pdf | delivered |
| VBF-C1T1R1-BOM-001 | Bill of materials (parameter BOM) | bom.xlsx / .pdf | delivered |
| VBF-C1T1R1-DSH-001 | Cell datasheet | datasheet.md / .pdf | delivered |
| VBF-C1T1R1-CALC-001 | Energy-density calculation record | calc.xlsx / .pdf | delivered |
| VBF-C1T1R1-DVPR-001 | Design verification plan and report | dvpr.md / .pdf | delivered |
| VBF-C1T1R1-DFMEA-001 | Design FMEA | dfmea.md / .pdf | delivered |
| VBF-C1T1R1-IDX-001 | This index | delivery_index.md / .pdf | delivered |

Supporting artifacts (workspace): log.jsonl (24-entry audit chain, mechanically
evaluated), design_plan.md, work/params/*.json (all variant parameter files),
cell/*.json (simulation outputs), validation/*.json (thermal-runaway outputs).
Final adjudication: final entry verdict = pass; champion = R4-V3-margin.
"""
md_pdf('delivery_index', delivery_index)

# ---------------------------------------------------------------- xlsx
wb = Workbook()
ws = wb.active
ws.title = 'BOM'
ws.append(['Item', 'Component', 'Parameter', 'Champion value', 'Unit', 'Source'])
bom_rows = [
    [1, 'Current collector (+)', 'Positive current collector thickness [m]', 8e-6, 'm', 'override work/params/r4_v3_margin.json (base 16e-6)'],
    [2, 'Current collector (-)', 'Negative current collector thickness [m]', 6e-6, 'm', 'override (base 12e-6)'],
    [3, 'Separator', 'Separator thickness [m]', 8e-6, 'm', 'override (base 12e-6)'],
    [4, 'Separator', 'Separator porosity', 0.55, '-', 'override (base 0.47)'],
    [5, 'Electrolyte', 'Cation transference number', 0.7, '-', 'override (base 0.2594)'],
    [6, 'Electrolyte', 'Electrolyte diffusivity [m2.s-1]', 2e-9, 'm2/s', 'override (base Nyman2008 fn)'],
    [7, 'Electrolyte', 'Electrolyte conductivity [S.m-1]', 3.0, 'S/m', 'override (base Nyman2008 fn)'],
    [8, 'Negative electrode', 'Negative particle radius [m]', 3e-6, 'm', 'override (base 5.86e-6)'],
    [9, 'Thermal management', 'Total heat transfer coefficient [W.m-2.K-1]', 100.0, 'W/m2/K', 'override (base 10)'],
    [10, 'Positive electrode', 'Positive electrode thickness [m]', 75.6e-6, 'm', 'Chen2020 base (unchanged)'],
    [11, 'Negative electrode', 'Negative electrode thickness [m]', 85.2e-6, 'm', 'Chen2020 base (unchanged)'],
    [12, 'Positive electrode', 'Positive particle radius [m]', 5.22e-6, 'm', 'Chen2020 base (unchanged)'],
    [13, 'Cell geometry', 'Electrode area [m2]', 0.1027, 'm2', 'calc-energy output (0.065 x 1.58 m)'],
]
for r in bom_rows:
    ws.append(r)
wb.save(DELIV / 'bom.xlsx')

wb2 = Workbook()
ws2 = wb2.active
ws2.title = 'Calc'
ws2.append(['Section', 'Quantity', 'Value', 'Unit', 'Source file'])
calc_rows = [
    ['Input', 'capacity_ah', 5.0306326667167305, 'Ah', 'cell/r4_v3_margin_energy.json'],
    ['Input', 'energy_wh', 17.89754980087133, 'Wh', 'cell/r4_v3_margin_energy.json'],
    ['Input', 'mass_kg', 0.0356025250776, 'kg', 'cell/r4_v3_margin_energy.json'],
    ['Input', 'area_m2', 0.10270000000000001, 'm2', 'cell/r4_v3_margin_energy.json'],
    ['Input', 'thickness_m', 0.0001828, 'm', 'cell/r4_v3_margin_energy.json'],
    ['Input', 'electrolyte_included', 'false', '-', 'cell/r4_v3_margin_energy.json'],
    ['Layer', 'positive_electrode layer_kg_m2', 0.163993788, 'kg/m2', 'cell/r4_v3_margin_energy.json'],
    ['Layer', 'negative_electrode layer_kg_m2', 0.1058823, 'kg/m2', 'cell/r4_v3_margin_energy.json'],
    ['Layer', 'positive_cc layer_kg_m2', 0.0216, 'kg/m2', 'cell/r4_v3_margin_energy.json'],
    ['Layer', 'negative_cc layer_kg_m2', 0.05376, 'kg/m2', 'cell/r4_v3_margin_energy.json'],
    ['Layer', 'separator layer_kg_m2', 0.0014292, 'kg/m2', 'cell/r4_v3_margin_energy.json'],
    ['Formula', 'ED = energy_wh / mass_kg', '17.8975498 / 0.0356025 = 502.7045', 'Wh/kg', 'calc-energy contract'],
    ['Result', 'energy_density_wh_kg', 502.7045065444505, 'Wh/kg', 'cell/r4_v3_margin_energy.json'],
    ['Result', 'energy_density_wh_l', 953.3380882939265, 'Wh/L', 'cell/r4_v3_margin_energy.json'],
    ['Check', 'ED threshold', 392.61, 'Wh/kg', 'entry-0 criteria stage2'],
    ['Check', 'ED >= threshold', 'PASS (+110.09)', '-', 'log-evaluate round 4'],
]
for r in calc_rows:
    ws2.append(r)
wb2.save(DELIV / 'calc.xlsx')

# PDFs for the two workbooks (text render of rows)
from openpyxl import load_workbook
for stem in ('bom', 'calc'):
    wbx = load_workbook(DELIV / f'{stem}.xlsx', read_only=True)
    lines = [f'{stem.upper()} - VBF-C1T1R1-{("BOM" if stem == "bom" else "CALC")}-001', '']
    for sh in wbx.worksheets:
        lines.append(f'[Sheet: {sh.title}]')
        for row in sh.iter_rows(values_only=True):
            lines.append(' | '.join('' if c is None else str(c) for c in row))
    make_pdf(DELIV / f'{stem}.pdf', f'VBF-C1T1R1 {stem} - Virtual Battery Factory deliverable', lines)

# config.yaml (goal only - optional input of bda render header)
(LEAK / 'config.yaml').write_text('goal: ' + json.dumps(GOAL, ensure_ascii=False) + '\n', encoding='utf-8')

print('deliverables written:', len(list(DELIV.iterdir())), 'files')
print('config.yaml goal written')
